spring.application.name=authentification
server.port=8084
# Configuration MySQL
spring.datasource.url=jdbc:postgresql://51.77.158.159:5432/symphonia_db?ssl=false
spring.datasource.username=super_symphonia
spring.datasource.password=1FBW2025!!
spring.datasource.driver-class-name=org.postgresql.Driver

# ESL
freeswitch:
host: 51.77.158.159
port: 8021
password: ClueCon

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Configuration swagger
# Configuration Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

# Configurer les origines autorisées
spring.webflux.cors.allowed-origins=http://localhost:8083
spring.webflux.cors.allowed-methods=GET, POST, PUT, DELETE, OPTIONS
spring.webflux.cors.allowed-headers=*


# Configuration gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raouia.ben19@gmail.com
spring.mail.password=kvyy iiai jjyp cvcp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true