spring.application.name=authentification
server.port=8084
# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/symphonya_auth?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Configuration swagger
# Configuration Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
# Configuration gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raouia.ben19@gmail.com
spring.mail.password=kvyy iiai jjyp cvcp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
